### ISSUE TITLE
Cannot import tiktoken into flask app - PyO3 modules may only be initialized once per interpreter process

### ISSUE THREAD

**Issue by simondpalmer** [openai/tiktoken#138]
I can load tiktoken locally with flask but once I try to use it on PythonAnywhere in production it errors with.
Both are using Python 3.10

```
Traceback (most recent call last):
  File "/home/simonpalmer/ideally/flask_api.py", line 11, in <module>
    import tiktoken
  File "/home/simonpalmer/.local/lib/python3.10/site-packages/tiktoken/__init__.py", line 1, in <module>
    from .core import Encoding as Encoding
  File "/home/simonpalmer/.local/lib/python3.10/site-packages/tiktoken/core.py", line 9, in <module>
    from tiktoken import _tiktoken
ImportError: PyO3 modules may only be initialized once per interpreter process
```

Which version of tiktoken has migrated to Py03?

**Comment by hauntsaninja** [comment]
This is the same issue you opened here: https://github.com/openai/tiktoken/issues/126 Please discuss there. In particular, create a reproducer.
