### ISSUE TITLE
Error: pyo3_runtime.PanicException assertion failed: encoder.len() == decoder.len()

### ISSUE THREAD

**Issue by osjason** [openai/tiktoken#87]
Here's an example of how you can structure your issue:

### Env

run  `pip list`

```
Package                Version
---------------------- --------------
aiohttp                3.8.4
aiosignal              1.3.1
anyio                  3.6.2
apturl                 0.5.2
async-timeout          4.0.2
attrs                  22.2.0
bcrypt                 3.2.0
blinker                1.4
blobfile               2.0.1
Brlapi                 0.8.3
certifi                2020.6.20
cffi                   1.15.1
chardet                4.0.0
charset-normalizer     3.1.0
click                  8.0.3
colorama               0.4.4
command-not-found      0.3
cryptography           3.4.8
cupshelpers            1.0
dblatex                0.3.12
dbus-python            1.2.18
defer                  1.0.6
distro                 1.7.0
distro-info            1.1build1
dlib                   19.16.0
duplicity              0.8.21
eg                     1.2.2
fasteners              0.14.1
filelock               3.9.0
frozenlist             1.3.3
future                 0.18.2
gpg                    1.16.0-unknown
h11                    0.14.0
httpcore               0.16.3
httplib2               0.20.2
httpx                  0.23.3
idna                   3.3
importlib-metadata     4.6.4
iotop                  0.6
jeepney                0.7.1
keyring                23.5.0
language-selector      0.1
launchpadlib           1.10.16
lazr.restfulclient     0.14.4
lazr.uri               1.0.6
libvirt-python         8.0.0
lockfile               0.12.2
louis                  3.20.0
lxml                   4.9.2
macaroonbakery         1.3.1
Mako                   1.1.3
MarkupSafe             2.0.1
monotonic              1.6
more-itertools         8.10.0
multidict              6.0.4
netifaces              0.11.0
numpy                  1.24.2
oauthlib               3.2.0
olefile                0.46
openai                 0.27.2
OpenAIAuth             0.3.2
opencv-python          4.6.0.66
paramiko               2.9.3
pexpect                4.8.0
Pillow                 9.0.1
pip                    23.0.1
prompt-toolkit         3.0.38
protobuf               3.12.4
ptyprocess             0.7.0
pycairo                1.20.1
pycparser              2.21
pycryptodomex          3.17
pycups                 2.0.1
PyGObject              3.42.1
PyJWT                  2.3.0
pymacaroons            0.13.0
PyNaCl                 1.5.0
pyparsing              2.4.7
PyQt5                  5.15.9
pyqt5-plugins          5.15.9.2.3
PyQt5-Qt5              5.15.2
PyQt5-sip              12.11.1
pyqt5-tools            5.15.9.3.3
pyRFC3339              1.1
PySocks                1.7.1
python-apt             2.4.0+ubuntu1
python-dateutil        2.8.1
python-debian          0.1.43ubuntu1
python-dotenv          1.0.0
pytz                   2022.1
pyxdg                  0.27
PyYAML                 5.4.1
qt5-applications       5.15.2.2.3
qt5-tools              5.15.2.1.3
regex                  2022.10.31
reportlab              3.6.8
requests               2.28.2
retrying               1.3.4
revChatGPT             4.0.11
rfc3986                1.5.0
SecretStorage          3.3.1
setuptools             59.6.0
six                    1.16.0
sniffio                1.3.0
socksio                1.0.0
ssh-import-id          5.11
systemd-python         234
tiktoken               0.3.3
tqdm                   4.65.0
ubuntu-advantage-tools 8001
ubuntu-drivers-common  0.0.0
ufw                    0.36.1
unattended-upgrades    0.1
urllib3                1.26.5
usb-creator            0.3.7
vboxapi                1.0
wadllib                1.3.6
wcwidth                0.2.6
wheel                  0.37.1
xdg                    5
xkit                   0.0.0
yarl                   1.8.2
zipp                   1.0.0
```

run `uname -a`
```
Linux jasonos-WU 5.19.0-38-generic #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

python version
```
Python 3.10.6
```

### Description

I ran into an assertion error while trying to run the project on Ubuntu 22.04 with Python 3.10. The error message reads as follows:

```
thread '<unnamed>' panicked at 'assertion failed: encoder.len() == decoder.len()', src/lib.rs:458:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jasonos/.local/lib/python3.10/site-packages/revChatGPT/V3.py", line 556, in <module>
    main()
  File "/home/jasonos/.local/lib/python3.10/site-packages/revChatGPT/V3.py", line 549, in main
    for query in chatbot.ask_stream(prompt):
  File "/home/jasonos/.local/lib/python3.10/site-packages/revChatGPT/V3.py", line 154, in ask_stream
    self.__truncate_conversation(convo_id=convo_id)
  File "/home/jasonos/.local/lib/python3.10/site-packages/revChatGPT/V3.py", line 94, in __truncate_conversation
    self.get_token_count(convo_id) > self.truncate_limit
  File "/home/jasonos/.local/lib/python3.10/site-packages/revChatGPT/V3.py", line 121, in get_token_count
    encoding = tiktoken.encoding_for_model("gpt-4-32k-0314")
  File "/home/jasonos/.local/lib/python3.10/site-packages/tiktoken/model.py", line 67, in encoding_for_model
    return get_encoding(model_encoding_name)
  File "/home/jasonos/.local/lib/python3.10/site-packages/tiktoken/registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
  File "/home/jasonos/.local/lib/python3.10/site-packages/tiktoken/core.py", line 50, in __init__
    self._core_bpe = _tiktoken.CoreBPE(mergeable_ranks, special_tokens, pat_str)
pyo3_runtime.PanicException: assertion failed: encoder.len() == decoder.len()
```

After some investigation, I discovered that one of the dictionary variables, `mergeable_ranks`.
and i print it :
```
mergeable_ranks: {b'!': 0, b'"': 1, b'#': 2, b'$': 3, b'%': 4,..., b'Application': 5095, b'legate': 5096, b' takes': 5}
```
it had a rank that wasn't in sequential order. The last key in the `mergeable_ranks` dictionary had a rank of 5, which caused the assertion error. so why ?
 
I try to fix the issue, I added the following code in core.py, line 50 :

```python
# FIXBUG
lastRankNum = mergeable_ranks[list(mergeable_ranks.keys())[-2]] + 1
mergeable_ranks[list(mergeable_ranks.keys())[-1]] = lastRankNum
self._mergeable_ranks = mergeable_ranks
```
Having not submit a pull request yet. I'm sharing this issue in case someone else is experiencing the same problem.

**Comment by hauntsaninja** [comment]
It's not the order, it's probably that you have two tokens with the same value.

**Comment by hauntsaninja** [comment]
The next release of tiktoken will mention this in the error message

**Comment by Degree-21** [comment]
Has this problem been solved

**Comment by RajNS02** [comment]
@osjason I was facing the same error out of nowhere!!
Thank you so much for the fix!
