### ISSUE TITLE
Installing paddleocr>=2.6.1.0, TomlError happend

### ISSUE THREAD

**Issue by luoshenfu** [openai/tiktoken#90]
pip37 install "paddleocr>=2.6.1.0" --user

**the result as below:**

Collecting rapidfuzz (from paddleocr>=2.6.1.0)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/15/e5/2ab8375be6955aff1925b69c41429cbe54e32a67461c0b59f94c9b8b1cc5/rapidfuzz-2.13.7.tar.gz
Exception:
Traceback (most recent call last):
  File "/usr/local/python37/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/usr/local/python37/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 315, in run
    resolver.resolve(requirement_set)
  File "/usr/local/python37/lib/python3.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/python37/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/python37/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/local/python37/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 349, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/local/python37/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 109, in prep_for_dist
    self.req.load_pyproject_toml()
  File "/usr/local/python37/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 489, in load_pyproject_toml
    str(self)
  File "/usr/local/python37/lib/python3.7/site-packages/pip/_internal/pyproject.py", line 66, in load_pyproject_toml
    pp_toml = pytoml.load(f)
  File "/usr/local/python37/lib/python3.7/site-packages/pip/_vendor/pytoml/parser.py", line 11, in load
    return loads(fin.read(), translate=translate, object_pairs_hook=object_pairs_hook, filename=getattr(fin, 'name', repr(fin)))
  File "/usr/local/python37/lib/python3.7/site-packages/pip/_vendor/pytoml/parser.py", line 24, in loads
    ast = _p_toml(src, object_pairs_hook=object_pairs_hook)
  File "/usr/local/python37/lib/python3.7/site-packages/pip/_vendor/pytoml/parser.py", line 340, in _p_toml
    s.expect_eof()
  File "/usr/local/python37/lib/python3.7/site-packages/pip/_vendor/pytoml/parser.py", line 125, in expect_eof
    return self._expect(self.consume_eof())
  File "/usr/local/python37/lib/python3.7/site-packages/pip/_vendor/pytoml/parser.py", line 165, in _expect
    raise TomlError('msg', self._pos[0], self._pos[1], self._filename)
pip._vendor.pytoml.core.TomlError: /tmp/pip-install-iyycc80g/rapidfuzz/pyproject.toml(28, 1): msg
You are using pip version 19.0.3, however version 23.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by hauntsaninja** [comment]
You're using an absolutely ancient version of pip. Please upgrade.

**Comment by luoshenfu** [comment]
> 

ok, thx, solved.
